databases:
  - name: erizel001
    plan: free
    databaseName: postgressql_sy9w
    user: postgressql_sy9w_user

services:
  - type: web
    plan: free
    name: erizel001
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn bankrates.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgressql_sy9w
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4