# Generated by Django 5.1.6 on 2025-02-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_currency_alter_exchangerate_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
