# Generated by Django 5.1.6 on 2025-06-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bank_options_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='branch_adverts/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_adverts', to='main.branch')),
            ],
            options={
                'verbose_name': 'Branch Advert',
                'verbose_name_plural': 'Branch Adverts',
            },
        ),
    ]
