# Generated by Django 5.1.6 on 2025-06-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_branchadvert'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchadvert',
            name='text',
            field=models.TextField(blank=True, help_text='Branch Advert text', null=True),
        ),
        migrations.AlterField(
            model_name='branchadvert',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='branch_adverts/'),
        ),
        migrations.AlterField(
            model_name='branchadvert',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], default='image', max_length=10),
        ),
    ]
