# Generated by Django 5.1.6 on 2025-06-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_branchadvert_text_alter_branchadvert_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='password',
            field=models.CharField(default='12345678', max_length=255),
        ),
    ]
