# Generated by Django 5.1.6 on 2025-07-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_branch_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
