# Generated by Django 5.1.6 on 2025-07-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_branch_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
