# Generated by Django 5.1.6 on 2025-07-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_bank_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
    ]
